// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bigsxnbpcrvlpyjumpmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpZ3N4bmJwY3J2bHB5anVtcG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NDgwMTQsImV4cCI6MjA5MDUyNDAxNH0.fDwXRGiY407zUrxTVValNYmuSY-38-st9A290_aVK6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});